// ERRORS ACTIONS
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


//AUTH ACTIONS
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';


//PAGE ACTIONS
export const PAGE_LOADING = 'PAGE_LOADING';
export const PAGE_LOADED = 'PAGE_LOADED';

//DASHBOARD ACTIONS
export const SET_DASHBOARD = 'SET_DASHBOARD';


// VENDORS ACTION
export const SET_VENDORS = 'SET_VENDORS';
export const SET_SINGLE_VENDOR = 'SET_SINGLE_VENDOR';


//USERS ACTION
export const SET_USERS = 'SET_USERS';
export const SET_SINGLE_USER = 'SET_SINGLE_USER';
export const SET_USER_STATE = 'SET_USER_STATE';

