// ERRORS ACTIONS
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


//AUTH ACTIONS
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_VENDOR = 'CREATE_VENDOR';
export const OTP_AUTHENTICATE_SUCCESS = 'OTP_AUTHENTICATE_SUCCESS';
export const OTP_AUTHENTICATE_FAIL = 'OTP_AUTHENTICATE_FAIL';


//PAGE ACTIONS
export const PAGE_LOADING = 'PAGE_LOADING';
export const PAGE_LOADED = 'PAGE_LOADED';
export const SET_INDEX_DATA = 'SET_INDEX_DATA';

//USERS ACTION
export const SET_VENDORS = 'SET_VENDORS';
export const SET_SINGLE_VENDOR = 'SET_SINGLE_VENDOR';


