// ERRORS ACTIONS
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


//AUTH ACTIONS
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';


//PAGE ACTIONS
export const PAGE_LOADING = 'PAGE_LOADING';
export const PAGE_LOADED = 'PAGE_LOADED';
export const SET_HOME_DATA = 'SET_HOME_DATA';

//USERS ACTION
export const SET_VENDORS = 'SET_VENDORS';
export const SET_SINGLE_VENDOR = 'SET_SINGLE_VENDOR';


